spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: ${url}
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
logging:
  level:
    sql: debug
    root: info