spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:news
    username: test
    password: test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
logging:
  level:
    sql: debug