spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    url: ${Db.url}
    username: ${Db.username}
    password: ${Db.password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1010758513764-vkahs9bmgab174ov7qmcrv9p95rt0v1t.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth?prompt=select_account

logging:
  level:
    sql: debug
    org.springframework.security: DEBUG
    com.redmath: TRACE

jwt:
  signing:
    key: 12345678900123456789012345678912

management:
  endpoints:
    web:
      exposure:
        include: "*"
#  tracing:
#    sampling:
#      probability: 1
#  otlp:
#    tracing:
#      endpoint: http://localhost:8082/v1/traces
#      export:
#        enabled: true
